### ISSUE TITLE
js_import does not resolve in a component referenced in broadcast code

### ISSUE THREAD

**Issue by jamauro** [bartblast/hologram#998]
**Describe the bug**

A component that declares a `js_import` and is referenced in broadcast caller code has its JS bindings silently dropped, so `JS.call/2` invokes undefined at runtime.

`Hologram.Compiler.aggregate_js_imports/1` is called only from `build_page_js/6`. `build_runtime_js/5` never calls it, so the runtime bundle emits neither the import statement nor the Interpreter.registerJsBindings(...) call. In 0.11, `CallGraph.list_runtime_mfas/2` pulls broadcast-referenced components into the runtime bundle — and any `js_import` they declare is lost. `resolveBinding/2` then falls through to `globalThis[name]`, which is undefined.

The failure names neither the binding nor the module: you get `TypeError: s is not a function` from a minified frame.

**Reproduction Repository**

https://github.com/jamauro/hologram-js-import-repro

 **To Reproduce**

1. mix deps.get && mix holo
2. Open http://localhost:4000/second and click Call JS
3. The label stays (not called yet); the console shows uncaught TypeError: s is not a function
4. grep -c shout priv/static/hologram/runtime-*.js → the component's JS is in the runtime bundle
5. grep -o 'registerJsBindings({' priv/static/hologram/*.js → no bundle emits a registration
6. Delete command/3 from app/second_page.ex and restart: without the broadcast reference the component stays in the page bundles, which do register the binding, and the button works

**Expected behavior**

The label becomes IT WORKS. A js_import should resolve regardless of which bundle the declaring module is compiled into.

**Environment information**

- Hologram version: 0.11.0 (works on 0.10.1 with identical application code)
- Elixir version: 1.20.0
- Erlang/OTP version: 29 [erts-17.0.1]
- Node.js version: 24.13.1
- Operating System: macOS 15.3.1
- Browser: Chrome 151.0.7922.108
  
**Additional context**

Found while upgrading an app from 0.10 to 0.11.

The fix we're running locally is to call `aggregate_js_imports/1` on runtime_mfas  inside `build_runtime_js/5`, then emit the import statements and the registration call the same way `build_page_js/6` already does. It reuses the existing helpers, so it's about 20 lines and introduces no new machinery. The compiler suite stays green and the repro above goes from s is not a function to IT WORKS.

**Comment by bartblast** [comment]
Fixed in #1086, merged to master.

Your diagnosis was correct. The runtime builder now aggregates JS imports like the page builder does. I added one rule on top of what you proposed - the runtime script owns the bindings for every module it bundles, and page bundles skip those modules. Otherwise a module that lands in both bundles (a broadcast-referenced component with a plain function that a page also calls) would get its JS imported and evaluated twice on the same page.

The client raises now too, instead of falling through to undefined. Same failure reads `there is no JS binding or global named "shout" in scope in MyApp.MyComponent (is a js_import declaration missing?)`.

Heads up on one thing: JS deps of broadcast-referenced components now end up in runtime.js, which every page loads, so they're no longer page-scoped.

Thanks for the repro repo and for reporting this, @jamauro! :)
